In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
business_df = pd.read_csv('rw_business_updating.csv')

In [3]:
review_df = pd.read_csv('rw_review.csv')

In [4]:
user_df = pd.read_csv('rw_user.csv')

In [5]:
review_df

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1
...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1

In [6]:
# Merge review with user data
merged_df = review_df.merge(user_df, left_on='user_id', right_on='user_id', how='left')

# Merge the result with business data
final_df = merged_df.merge(business_df, left_on='business_id', right_on='business_id', how='left')

In [7]:
final_df

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,name_x,...,gender,age,longitude_x,latitude_x,name_y,latitude_y,longitude_y,categories,stars,review_count_y
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,M,25,30.741748,-1.813194,Gen-Z Comedy Show,-1.957937,30.062312,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,F,40,30.574140,-1.791345,Azizi Life,-2.147947,29.753094,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,F,38,29.814018,-2.284000,Lavana,-1.960017,30.083126,"Pizza, Restaurants",4.4,506.0
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,F,39,30.648322,-2.339266,KIGALI FIT,-1.935761,30.109916,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,M,27,29.048602,-2.591968,Isange One Stop Center Gahini Hospital,-1.846441,30.477075,"Local Services, Community Service/Non-Profit, ...",0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1,William,...,M,32,29.434285,-2.006153,NaN,NaN,NaN,"Arts & Entertainment, Cinema",NaN,NaN
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1,Yingbo,...,N,29,30.238544,-2.034223,NaN,NaN,NaN,"Nail Salons, Beauty & Spas, Massage, Waxing, H...",NaN,NaN
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1,Alyse,...,F,32,30.430595,-1.121430,NaN,NaN,NaN,"Automotive, Tires, Auto Parts & Supplies, Auto...",NaN,NaN
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1,Syreeta,...,N,38,29.347848,-2.516060,NaN,NaN,NaN,"Tires, Auto Repair, Automotive, Oil Change Sta...",NaN,NaN
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1,Laura,...,F,31,29.817777,-1.996873,Blue Oceans Rwanda,-1.953642,30.098285,"Climbing, Active Life, Fitness & Instruction, ...",5.0,3.0

In [8]:
df = final_df.rename(columns={'name_x': 'user_name', 'name_y': 'business_name'})

In [9]:
df.columns

Index(['review_id', 'user_id', 'business_id', 'text', 'date', 'service_name',
       'state', 'rec_score', 'q_responses', 'user_name', 'review_count_x',
       'friends', 'average_stars', 'gender', 'age', 'longitude_x',
       'latitude_x', 'business_name', 'latitude_y', 'longitude_y',
       'categories', 'stars', 'review_count_y'],
      dtype='object')

In [10]:
# Combine latitude and longitude into a single column
df['business_address'] = df['latitude_y'].astype(str) + ', ' + df['longitude_y'].astype(str)
df['user_address'] = df['latitude_x'].astype(str) + ', ' + df['longitude_x'].astype(str)

In [11]:
df

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,user_name,...,longitude_x,latitude_x,business_name,latitude_y,longitude_y,categories,stars,review_count_y,business_address,user_address
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,30.741748,-1.813194,Gen-Z Comedy Show,-1.957937,30.062312,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0,"-1.957937, 30.062312","-1.8131935334722813, 30.74174803504553"
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,30.574140,-1.791345,Azizi Life,-2.147947,29.753094,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0,"-2.1479474, 29.7530937","-1.7913448254857884, 30.57414039025001"
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,29.814018,-2.284000,Lavana,-1.960017,30.083126,"Pizza, Restaurants",4.4,506.0,"-1.9600167, 30.0831264","-2.284000461592804, 29.81401787261076"
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,30.648322,-2.339266,KIGALI FIT,-1.935761,30.109916,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0,"-1.9357612, 30.1099164","-2.3392663890148504, 30.648322179028003"
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,29.048602,-2.591968,Isange One Stop Center Gahini Hospital,-1.846441,30.477075,"Local Services, Community Service/Non-Profit, ...",0.0,0.0,"-1.8464408, 30.4770747","-2.5919683832664204, 29.048602363295014"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1,William,...,29.434285,-2.006153,NaN,NaN,NaN,"Arts & Entertainment, Cinema",NaN,NaN,"nan, nan","-2.006153287347627, 29.434284651143"
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1,Yingbo,...,30.238544,-2.034223,NaN,NaN,NaN,"Nail Salons, Beauty & Spas, Massage, Waxing, H...",NaN,NaN,"nan, nan","-2.034222796718606, 30.238543990488573"
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1,Alyse,...,30.430595,-1.121430,NaN,NaN,NaN,"Automotive, Tires, Auto Parts & Supplies, Auto...",NaN,NaN,"nan, nan","-1.1214298395687634, 30.43059497249931"
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1,Syreeta,...,29.347848,-2.516060,NaN,NaN,NaN,"Tires, Auto Repair, Automotive, Oil Change Sta...",NaN,NaN,"nan, nan","-2.5160600379073057, 29.347847577202504"
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1,Laura,...,29.817777,-1.996873,Blue Oceans Rwanda,-1.953642,30.098285,"Climbing, Active Life, Fitness & Instruction, ...",5.0,3.0,"-1.953642, 30.0982853","-1.9968726163206127, 29.817777424986986"

In [12]:
df = df.drop(['longitude_x', 'longitude_y','latitude_y','latitude_x'], axis=1)

In [13]:
df

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,user_name,...,friends,average_stars,gender,age,business_name,categories,stars,review_count_y,business_address,user_address
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,"ZaUT63HFjheiub1y7019Yg, Obkepp5aBTYVX-AL4zwBoQ...",4.44,M,25,Gen-Z Comedy Show,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0,"-1.957937, 30.062312","-1.8131935334722813, 30.74174803504553"
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,"V9LEewSb9wmmyLeW9gEySw, zqh0Gm8TLOQmU1ayg-DPDg...",3.92,F,40,Azizi Life,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0,"-2.1479474, 29.7530937","-1.7913448254857884, 30.57414039025001"
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,"8VyYj63y30bagiHz_pqJUw, Vm0fyrUjwMTDgwqV6DhqDw...",4.41,F,38,Lavana,"Pizza, Restaurants",4.4,506.0,"-1.9600167, 30.0831264","-2.284000461592804, 29.81401787261076"
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,"llPe4d3OC8gHkXgWIAnasQ, fp9uTSoe74XLhY6HNsjEew...",4.35,F,39,KIGALI FIT,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0,"-1.9357612, 30.1099164","-2.3392663890148504, 30.648322179028003"
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,"sZaRJwINk4-V8o06kFeo2A, ZwyRFQWEzh4rGEyvlr5Oeg...",3.53,M,27,Isange One Stop Center Gahini Hospital,"Local Services, Community Service/Non-Profit, ...",0.0,0.0,"-1.8464408, 30.4770747","-2.5919683832664204, 29.048602363295014"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1,William,...,"ZQjsNntf0RQh3eJSP2EYEA, Y_2jMUKz6pvJ0JSWG3u10A...",4.17,M,32,NaN,"Arts & Entertainment, Cinema",NaN,NaN,"nan, nan","-2.006153287347627, 29.434284651143"
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1,Yingbo,...,"xbhUhCSeeFg-Cm2oEIejNw, k1tSWm6mdPL-dendMa69gA...",3.47,N,29,NaN,"Nail Salons, Beauty & Spas, Massage, Waxing, H...",NaN,NaN,"nan, nan","-2.034222796718606, 30.238543990488573"
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1,Alyse,...,"acLOor4HFm1IuyEfT08ECw, vLmXgY5Nm3frJzCsDW_5hQ...",3.59,F,32,NaN,"Automotive, Tires, Auto Parts & Supplies, Auto...",NaN,NaN,"nan, nan","-1.1214298395687634, 30.43059497249931"
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1,Syreeta,...,"bhAB5wo9iLsaExSw4apR4g, RyJsWkFLJHkf1Lif0cr3lg...",3.74,N,38,NaN,"Tires, Auto Repair, Automotive, Oil Change Sta...",NaN,NaN,"nan, nan","-2.5160600379073057, 29.347847577202504"
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1,Laura,...,"_BcWyKQL16ndpBdggh2kNA, lGZJfjOcMOF4peqc1-YpnA...",3.84,F,31,Blue Oceans Rwanda,"Climbing, Active Life, Fitness & Instruction, ...",5.0,3.0,"-1.953642, 30.0982853","-1.9968726163206127, 29.817777424986986"

In [14]:
df.isnull().sum()

review_id              0
user_id                0
business_id            0
text                   0
date                   0
service_name         777
state                  0
rec_score              0
q_responses            0
user_name              0
review_count_x         0
friends              325
average_stars          0
gender                 0
age                    0
business_name       4357
categories             0
stars               4367
review_count_y      4367
business_address       0
user_address           0
dtype: int64

In [15]:
df = df.rename(columns={'name_x': 'user_name', 'name_y': 'business_name'})

In [16]:
df = df.rename(columns={'review_count_x': 'review_count_users', 'review_count_y': 'review_count_business'})

In [17]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13442 entries, 0 to 13441
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   review_id              13442 non-null  object
 1   user_id                13442 non-null  object
 2   business_id            13442 non-null  object
 3   text                   13442 non-null  object
 4   date                   13442 non-null  object
 5   service_name           12665 non-null  object
 6   state                  13442 non-null  int64
 7   rec_score              13442 non-null  int64
 8   q_responses            13442 non-null  int64
 9   user_name              13442 non-null  object
 10  review_count_users     13442 non-null  int64
 11  friends                13117 non-null  object
 12  average_stars          13442 non-null  float64
 13  gender                 13442 non-null  object
 14  age                    13442 non-null  int64
 15  business_name          9085 non-null   object
 16  categories             13442 non-null  object
 17  stars                  9075 non-null   float64
 18  review_count_business  9075 non-null   float64
 19  business_address       13442 non-null  object
 20  user_address           13442 non-null  object
dtypes: float64(3), int64(5), object(13)
memory usage: 2.2+ MB
None

In [18]:
# Function to clean and convert values
def clean_and_convert(value):
    if pd.isna(value):
        return np.nan
    value = str(value).strip("[]'")  # Remove extraneous characters
    try:
        return int(value)
    except ValueError:
        return np.nan

In [19]:
# # Apply the cleaning and conversion function
# df['potential_ages'] = df['potential_ages'].apply(clean_and_convert)

# # Handle NaN values (e.g., fill with 0) and convert to integer
# df['potential_ages'] = df['potential_ages'].fillna(0).astype(int)

In [20]:
df.head()

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,user_name,...,friends,average_stars,gender,age,business_name,categories,stars,review_count_business,business_address,user_address
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,"ZaUT63HFjheiub1y7019Yg, Obkepp5aBTYVX-AL4zwBoQ...",4.44,M,25,Gen-Z Comedy Show,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0,"-1.957937, 30.062312","-1.8131935334722813, 30.74174803504553"
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,"V9LEewSb9wmmyLeW9gEySw, zqh0Gm8TLOQmU1ayg-DPDg...",3.92,F,40,Azizi Life,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0,"-2.1479474, 29.7530937","-1.7913448254857884, 30.57414039025001"
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,"8VyYj63y30bagiHz_pqJUw, Vm0fyrUjwMTDgwqV6DhqDw...",4.41,F,38,Lavana,"Pizza, Restaurants",4.4,506.0,"-1.9600167, 30.0831264","-2.284000461592804, 29.81401787261076"
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,"llPe4d3OC8gHkXgWIAnasQ, fp9uTSoe74XLhY6HNsjEew...",4.35,F,39,KIGALI FIT,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0,"-1.9357612, 30.1099164","-2.3392663890148504, 30.648322179028003"
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,"sZaRJwINk4-V8o06kFeo2A, ZwyRFQWEzh4rGEyvlr5Oeg...",3.53,M,27,Isange One Stop Center Gahini Hospital,"Local Services, Community Service/Non-Profit, ...",0.0,0.0,"-1.8464408, 30.4770747","-2.5919683832664204, 29.048602363295014"

In [21]:
# # Function to generate random names
# def generate_random_name():
#     names = ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Henry', 'Isla', 'Jack']
#     return np.random.choice(names)

# # Fill missing values in user_name
# df['user_name'] = df['user_name'].fillna(df['user_name'].apply(lambda x: generate_random_name() if pd.isna(x) else x))

# # Fill missing values in review_count_users
# df['review_count_users'] = df['review_count_users'].fillna(df['review_count_users'].mean().round())

# # Fill missing values in friends
# def generate_random_friends():
#     return ', '.join(np.random.choice(list('ABCDEFGHIJKLMNOPQRSTUVWXYZ'), size=np.random.randint(1, 5)))

# df['friends'] = df['friends'].fillna(df['friends'].apply(lambda x: generate_random_friends() if pd.isna(x) else x))

# # Fill missing values in average_stars
# df['average_stars'] = df['average_stars'].fillna(df['average_stars'].mean().round(2))

# # Fill missing values in gender
# df['gender'] = df['gender'].fillna(np.random.choice(['M', 'F']))

# # Fill missing values in potential_ages
# df['potential_ages'] = df['potential_ages'].fillna(df['potential_ages'].apply(lambda x: np.random.randint(18, 70) if pd.isna(x) else x))

# Fill missing values in business_name
def generate_random_business_name():
    prefixes = ['The', 'Little', 'Big', 'Golden', 'Silver', 'Blue', 'Red', 'Green']
    suffixes = ['Cafe', 'Restaurant', 'Hotel', 'Store', 'Shop', 'Bistro', 'Diner', 'Inn']
    return f"{np.random.choice(prefixes)} {np.random.choice(suffixes)}"

df['business_name'] = df['business_name'].fillna(df['business_name'].apply(lambda x: generate_random_business_name() if pd.isna(x) else x))

# Fill missing values in stars
df['stars'] = df['stars'].fillna(df['stars'].mean().round(1))

# Fill missing values in review_count_business
df['review_count_business'] = df['review_count_business'].fillna(df['review_count_business'].mean().round())

# Print the updated dataset
# print(df)

# # Save the updated dataset
# df.to_csv('updated_dataset.csv', index=False)

In [22]:
# Fill missing values in friends
def generate_random_friends():
    return ', '.join(np.random.choice(list('ABCDEFGHIJKLMNOPQRSTUVWXYZ'), size=np.random.randint(1, 5)))

df['friends'] = df['friends'].fillna(df['friends'].apply(lambda x: generate_random_friends() if pd.isna(x) else x))

# Fill missing values in average_stars
df['average_stars'] = df['average_stars'].fillna(df['average_stars'].mean().round(2))

# # Fill missing values in gender
# df['gender'] = df['gender'].fillna(np.random.choice(['M', 'F']))

# # Fill missing values in potential_ages
# df['potential_ages'] = df['age'].fillna(df['potential_ages'].apply(lambda x: np.random.randint(18, 70) if pd.isna(x) else x))

In [23]:
df

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,user_name,...,friends,average_stars,gender,age,business_name,categories,stars,review_count_business,business_address,user_address
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,"ZaUT63HFjheiub1y7019Yg, Obkepp5aBTYVX-AL4zwBoQ...",4.44,M,25,Gen-Z Comedy Show,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0,"-1.957937, 30.062312","-1.8131935334722813, 30.74174803504553"
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,"V9LEewSb9wmmyLeW9gEySw, zqh0Gm8TLOQmU1ayg-DPDg...",3.92,F,40,Azizi Life,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0,"-2.1479474, 29.7530937","-1.7913448254857884, 30.57414039025001"
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,"8VyYj63y30bagiHz_pqJUw, Vm0fyrUjwMTDgwqV6DhqDw...",4.41,F,38,Lavana,"Pizza, Restaurants",4.4,506.0,"-1.9600167, 30.0831264","-2.284000461592804, 29.81401787261076"
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,"llPe4d3OC8gHkXgWIAnasQ, fp9uTSoe74XLhY6HNsjEew...",4.35,F,39,KIGALI FIT,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0,"-1.9357612, 30.1099164","-2.3392663890148504, 30.648322179028003"
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,"sZaRJwINk4-V8o06kFeo2A, ZwyRFQWEzh4rGEyvlr5Oeg...",3.53,M,27,Isange One Stop Center Gahini Hospital,"Local Services, Community Service/Non-Profit, ...",0.0,0.0,"-1.8464408, 30.4770747","-2.5919683832664204, 29.048602363295014"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1,William,...,"ZQjsNntf0RQh3eJSP2EYEA, Y_2jMUKz6pvJ0JSWG3u10A...",4.17,M,32,Blue Shop,"Arts & Entertainment, Cinema",3.4,166.0,"nan, nan","-2.006153287347627, 29.434284651143"
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1,Yingbo,...,"xbhUhCSeeFg-Cm2oEIejNw, k1tSWm6mdPL-dendMa69gA...",3.47,N,29,Silver Restaurant,"Nail Salons, Beauty & Spas, Massage, Waxing, H...",3.4,166.0,"nan, nan","-2.034222796718606, 30.238543990488573"
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1,Alyse,...,"acLOor4HFm1IuyEfT08ECw, vLmXgY5Nm3frJzCsDW_5hQ...",3.59,F,32,Red Restaurant,"Automotive, Tires, Auto Parts & Supplies, Auto...",3.4,166.0,"nan, nan","-1.1214298395687634, 30.43059497249931"
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1,Syreeta,...,"bhAB5wo9iLsaExSw4apR4g, RyJsWkFLJHkf1Lif0cr3lg...",3.74,N,38,Green Store,"Tires, Auto Repair, Automotive, Oil Change Sta...",3.4,166.0,"nan, nan","-2.5160600379073057, 29.347847577202504"
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1,Laura,...,"_BcWyKQL16ndpBdggh2kNA, lGZJfjOcMOF4peqc1-YpnA...",3.84,F,31,Blue Oceans Rwanda,"Climbing, Active Life, Fitness & Instruction, ...",5.0,3.0,"-1.953642, 30.0982853","-1.9968726163206127, 29.817777424986986"

In [24]:
# def fill_potential_age(age):
#     if age == 0 or pd.isna(age):
#         return np.random.randint(18, 70)
#     return age

# df['potential_ages'] = df['potential_ages'].apply(fill_potential_age)

In [25]:
df

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,user_name,...,friends,average_stars,gender,age,business_name,categories,stars,review_count_business,business_address,user_address
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,"ZaUT63HFjheiub1y7019Yg, Obkepp5aBTYVX-AL4zwBoQ...",4.44,M,25,Gen-Z Comedy Show,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0,"-1.957937, 30.062312","-1.8131935334722813, 30.74174803504553"
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,"V9LEewSb9wmmyLeW9gEySw, zqh0Gm8TLOQmU1ayg-DPDg...",3.92,F,40,Azizi Life,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0,"-2.1479474, 29.7530937","-1.7913448254857884, 30.57414039025001"
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,"8VyYj63y30bagiHz_pqJUw, Vm0fyrUjwMTDgwqV6DhqDw...",4.41,F,38,Lavana,"Pizza, Restaurants",4.4,506.0,"-1.9600167, 30.0831264","-2.284000461592804, 29.81401787261076"
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,"llPe4d3OC8gHkXgWIAnasQ, fp9uTSoe74XLhY6HNsjEew...",4.35,F,39,KIGALI FIT,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0,"-1.9357612, 30.1099164","-2.3392663890148504, 30.648322179028003"
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,"sZaRJwINk4-V8o06kFeo2A, ZwyRFQWEzh4rGEyvlr5Oeg...",3.53,M,27,Isange One Stop Center Gahini Hospital,"Local Services, Community Service/Non-Profit, ...",0.0,0.0,"-1.8464408, 30.4770747","-2.5919683832664204, 29.048602363295014"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1,William,...,"ZQjsNntf0RQh3eJSP2EYEA, Y_2jMUKz6pvJ0JSWG3u10A...",4.17,M,32,Blue Shop,"Arts & Entertainment, Cinema",3.4,166.0,"nan, nan","-2.006153287347627, 29.434284651143"
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1,Yingbo,...,"xbhUhCSeeFg-Cm2oEIejNw, k1tSWm6mdPL-dendMa69gA...",3.47,N,29,Silver Restaurant,"Nail Salons, Beauty & Spas, Massage, Waxing, H...",3.4,166.0,"nan, nan","-2.034222796718606, 30.238543990488573"
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1,Alyse,...,"acLOor4HFm1IuyEfT08ECw, vLmXgY5Nm3frJzCsDW_5hQ...",3.59,F,32,Red Restaurant,"Automotive, Tires, Auto Parts & Supplies, Auto...",3.4,166.0,"nan, nan","-1.1214298395687634, 30.43059497249931"
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1,Syreeta,...,"bhAB5wo9iLsaExSw4apR4g, RyJsWkFLJHkf1Lif0cr3lg...",3.74,N,38,Green Store,"Tires, Auto Repair, Automotive, Oil Change Sta...",3.4,166.0,"nan, nan","-2.5160600379073057, 29.347847577202504"
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1,Laura,...,"_BcWyKQL16ndpBdggh2kNA, lGZJfjOcMOF4peqc1-YpnA...",3.84,F,31,Blue Oceans Rwanda,"Climbing, Active Life, Fitness & Instruction, ...",5.0,3.0,"-1.953642, 30.0982853","-1.9968726163206127, 29.817777424986986"

In [26]:
# df.to_csv('yelp_dataset_combined.csv', index=False)

In [27]:
import string

# Function to generate a single user ID
def generate_user_id():
    # Generate a 22-character string of random letters and numbers
    return ''.join(np.random.choice(list(string.ascii_letters + string.digits), size=22))

# Function to generate a list of friend user IDs
def generate_friend_list():
    num_friends = np.random.randint(1, 5)  # Random number of friends between 1 and 4
    return ', '.join(generate_user_id() for _ in range(num_friends))

# Fill missing values in friends column
df['friends'] = df['friends'].fillna(df['friends'].apply(lambda x: generate_friend_list() if pd.isna(x) else x))

In [28]:
df

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,user_name,...,friends,average_stars,gender,age,business_name,categories,stars,review_count_business,business_address,user_address
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,"ZaUT63HFjheiub1y7019Yg, Obkepp5aBTYVX-AL4zwBoQ...",4.44,M,25,Gen-Z Comedy Show,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0,"-1.957937, 30.062312","-1.8131935334722813, 30.74174803504553"
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,"V9LEewSb9wmmyLeW9gEySw, zqh0Gm8TLOQmU1ayg-DPDg...",3.92,F,40,Azizi Life,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0,"-2.1479474, 29.7530937","-1.7913448254857884, 30.57414039025001"
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,"8VyYj63y30bagiHz_pqJUw, Vm0fyrUjwMTDgwqV6DhqDw...",4.41,F,38,Lavana,"Pizza, Restaurants",4.4,506.0,"-1.9600167, 30.0831264","-2.284000461592804, 29.81401787261076"
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,"llPe4d3OC8gHkXgWIAnasQ, fp9uTSoe74XLhY6HNsjEew...",4.35,F,39,KIGALI FIT,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0,"-1.9357612, 30.1099164","-2.3392663890148504, 30.648322179028003"
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,"sZaRJwINk4-V8o06kFeo2A, ZwyRFQWEzh4rGEyvlr5Oeg...",3.53,M,27,Isange One Stop Center Gahini Hospital,"Local Services, Community Service/Non-Profit, ...",0.0,0.0,"-1.8464408, 30.4770747","-2.5919683832664204, 29.048602363295014"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1,William,...,"ZQjsNntf0RQh3eJSP2EYEA, Y_2jMUKz6pvJ0JSWG3u10A...",4.17,M,32,Blue Shop,"Arts & Entertainment, Cinema",3.4,166.0,"nan, nan","-2.006153287347627, 29.434284651143"
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1,Yingbo,...,"xbhUhCSeeFg-Cm2oEIejNw, k1tSWm6mdPL-dendMa69gA...",3.47,N,29,Silver Restaurant,"Nail Salons, Beauty & Spas, Massage, Waxing, H...",3.4,166.0,"nan, nan","-2.034222796718606, 30.238543990488573"
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1,Alyse,...,"acLOor4HFm1IuyEfT08ECw, vLmXgY5Nm3frJzCsDW_5hQ...",3.59,F,32,Red Restaurant,"Automotive, Tires, Auto Parts & Supplies, Auto...",3.4,166.0,"nan, nan","-1.1214298395687634, 30.43059497249931"
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1,Syreeta,...,"bhAB5wo9iLsaExSw4apR4g, RyJsWkFLJHkf1Lif0cr3lg...",3.74,N,38,Green Store,"Tires, Auto Repair, Automotive, Oil Change Sta...",3.4,166.0,"nan, nan","-2.5160600379073057, 29.347847577202504"
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1,Laura,...,"_BcWyKQL16ndpBdggh2kNA, lGZJfjOcMOF4peqc1-YpnA...",3.84,F,31,Blue Oceans Rwanda,"Climbing, Active Life, Fitness & Instruction, ...",5.0,3.0,"-1.953642, 30.0982853","-1.9968726163206127, 29.817777424986986"

In [29]:
# Function to generate a single user ID
def generate_user_id():
    return ''.join(np.random.choice(list(string.ascii_letters + string.digits), size=22))

# Function to generate a list of friend user IDs
def generate_friend_list():
    num_friends = np.random.randint(1, 5)  # Random number of friends between 1 and 4
    return ', '.join(generate_user_id() for _ in range(num_friends))

# Function to validate and potentially replace friend list
def validate_and_replace_friends(friends):
    if pd.isna(friends) or all(len(friend) < 3 for friend in friends.split(', ')):
        return generate_friend_list()
    return friends

# Apply the function to the friends column
df['friends'] = df['friends'].apply(validate_and_replace_friends)

In [30]:
# Approximate bounding box for Rwanda
RWANDA_MIN_LAT, RWANDA_MAX_LAT = -2.84, -1.05
RWANDA_MIN_LON, RWANDA_MAX_LON = 28.86, 30.90

# Function to generate a random point within Rwanda's approximate boundaries
def generate_rwanda_coordinates():
    lat = np.random.uniform(RWANDA_MIN_LAT, RWANDA_MAX_LAT)
    lon = np.random.uniform(RWANDA_MIN_LON, RWANDA_MAX_LON)
    return f"{lat:.7f}, {lon:.7f}"

# Function to check and replace invalid coordinates
def replace_invalid_coordinates(coord):
    if pd.isna(coord) or coord == 'nan, nan':
        return generate_rwanda_coordinates()
    try:
        lat, lon = map(float, coord.split(','))
        if (RWANDA_MIN_LAT <= lat <= RWANDA_MAX_LAT) and (RWANDA_MIN_LON <= lon <= RWANDA_MAX_LON):
            return coord
        else:
            return generate_rwanda_coordinates()
    except:
        return generate_rwanda_coordinates()

# Fill and validate business_address
df['business_address'] = df['business_address'].apply(replace_invalid_coordinates)

# Fill and validate user_address
df['user_address'] = df['user_address'].apply(replace_invalid_coordinates)

# # Save the updated dataset
# df.to_csv('updated_dataset.csv', index=False)

# print(df['business_address'].head(10))
# print(df['user_address'].head(10))

In [31]:
# Function to fill missing service_name based on existing values in the DataFrame
def fill_service_name(row, df):
    if pd.isnull(row['service_name']):
        # Find potential services from the same business name and categories
        potential_services = df[
            (df['business_name'] == row['business_name']) &
            (df['categories'] == row['categories']) &
            (df['service_name'].notnull())
        ]['service_name'].unique()
        
        if len(potential_services) > 0:
            return random.choice(potential_services)
    return row['service_name']

# Apply the function to fill in missing values
df['service_name'] = df.apply(lambda row: fill_service_name(row, df), axis=1)

In [32]:
def fill_remaining_service_name(row, df):
    if pd.isnull(row['service_name']):
        # Extract the category
        categories = row['categories'].split(', ')
        possible_services = []
        
        for category in categories:
            # Look for services in the same category across the entire DataFrame
            services_in_category = df[df['categories'].str.contains(category)]['service_name'].dropna().unique()
            possible_services.extend(services_in_category)
        
        if possible_services:
            return random.choice(possible_services)
    return row['service_name']

df['service_name'] = df.apply(lambda row: fill_remaining_service_name(row, df), axis=1)

C:\Users\bdalia\AppData\Local\Temp\ipykernel_28420\2848169922.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  services_in_category = df[df['categories'].str.contains(category)]['service_name'].dropna().unique()

In [33]:
df

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,user_name,...,friends,average_stars,gender,age,business_name,categories,stars,review_count_business,business_address,user_address
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,"ZaUT63HFjheiub1y7019Yg, Obkepp5aBTYVX-AL4zwBoQ...",4.44,M,25,Gen-Z Comedy Show,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0,"-1.957937, 30.062312","-1.8131935334722813, 30.74174803504553"
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,"V9LEewSb9wmmyLeW9gEySw, zqh0Gm8TLOQmU1ayg-DPDg...",3.92,F,40,Azizi Life,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0,"-2.1479474, 29.7530937","-1.7913448254857884, 30.57414039025001"
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,"8VyYj63y30bagiHz_pqJUw, Vm0fyrUjwMTDgwqV6DhqDw...",4.41,F,38,Lavana,"Pizza, Restaurants",4.4,506.0,"-1.9600167, 30.0831264","-2.284000461592804, 29.81401787261076"
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,"llPe4d3OC8gHkXgWIAnasQ, fp9uTSoe74XLhY6HNsjEew...",4.35,F,39,KIGALI FIT,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0,"-1.9357612, 30.1099164","-2.3392663890148504, 30.648322179028003"
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,"sZaRJwINk4-V8o06kFeo2A, ZwyRFQWEzh4rGEyvlr5Oeg...",3.53,M,27,Isange One Stop Center Gahini Hospital,"Local Services, Community Service/Non-Profit, ...",0.0,0.0,"-1.8464408, 30.4770747","-2.5919683832664204, 29.048602363295014"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1,William,...,"ZQjsNntf0RQh3eJSP2EYEA, Y_2jMUKz6pvJ0JSWG3u10A...",4.17,M,32,Blue Shop,"Arts & Entertainment, Cinema",3.4,166.0,"-2.8038270, 29.0267859","-2.006153287347627, 29.434284651143"
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1,Yingbo,...,"xbhUhCSeeFg-Cm2oEIejNw, k1tSWm6mdPL-dendMa69gA...",3.47,N,29,Silver Restaurant,"Nail Salons, Beauty & Spas, Massage, Waxing, H...",3.4,166.0,"-2.5931391, 30.4458866","-2.034222796718606, 30.238543990488573"
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1,Alyse,...,"acLOor4HFm1IuyEfT08ECw, vLmXgY5Nm3frJzCsDW_5hQ...",3.59,F,32,Red Restaurant,"Automotive, Tires, Auto Parts & Supplies, Auto...",3.4,166.0,"-1.5072895, 29.0210917","-1.1214298395687634, 30.43059497249931"
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1,Syreeta,...,"bhAB5wo9iLsaExSw4apR4g, RyJsWkFLJHkf1Lif0cr3lg...",3.74,N,38,Green Store,"Tires, Auto Repair, Automotive, Oil Change Sta...",3.4,166.0,"-1.8893421, 29.2845674","-2.5160600379073057, 29.347847577202504"
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1,Laura,...,"_BcWyKQL16ndpBdggh2kNA, lGZJfjOcMOF4peqc1-YpnA...",3.84,F,31,Blue Oceans Rwanda,"Climbing, Active Life, Fitness & Instruction, ...",5.0,3.0,"-1.953642, 30.0982853","-1.9968726163206127, 29.817777424986986"

In [34]:
df = df.rename(columns={'age': 'user_ages'})

In [35]:
df

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,user_name,...,friends,average_stars,gender,user_ages,business_name,categories,stars,review_count_business,business_address,user_address
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,"ZaUT63HFjheiub1y7019Yg, Obkepp5aBTYVX-AL4zwBoQ...",4.44,M,25,Gen-Z Comedy Show,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0,"-1.957937, 30.062312","-1.8131935334722813, 30.74174803504553"
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,"V9LEewSb9wmmyLeW9gEySw, zqh0Gm8TLOQmU1ayg-DPDg...",3.92,F,40,Azizi Life,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0,"-2.1479474, 29.7530937","-1.7913448254857884, 30.57414039025001"
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,"8VyYj63y30bagiHz_pqJUw, Vm0fyrUjwMTDgwqV6DhqDw...",4.41,F,38,Lavana,"Pizza, Restaurants",4.4,506.0,"-1.9600167, 30.0831264","-2.284000461592804, 29.81401787261076"
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,"llPe4d3OC8gHkXgWIAnasQ, fp9uTSoe74XLhY6HNsjEew...",4.35,F,39,KIGALI FIT,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0,"-1.9357612, 30.1099164","-2.3392663890148504, 30.648322179028003"
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,"sZaRJwINk4-V8o06kFeo2A, ZwyRFQWEzh4rGEyvlr5Oeg...",3.53,M,27,Isange One Stop Center Gahini Hospital,"Local Services, Community Service/Non-Profit, ...",0.0,0.0,"-1.8464408, 30.4770747","-2.5919683832664204, 29.048602363295014"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1,William,...,"ZQjsNntf0RQh3eJSP2EYEA, Y_2jMUKz6pvJ0JSWG3u10A...",4.17,M,32,Blue Shop,"Arts & Entertainment, Cinema",3.4,166.0,"-2.8038270, 29.0267859","-2.006153287347627, 29.434284651143"
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1,Yingbo,...,"xbhUhCSeeFg-Cm2oEIejNw, k1tSWm6mdPL-dendMa69gA...",3.47,N,29,Silver Restaurant,"Nail Salons, Beauty & Spas, Massage, Waxing, H...",3.4,166.0,"-2.5931391, 30.4458866","-2.034222796718606, 30.238543990488573"
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1,Alyse,...,"acLOor4HFm1IuyEfT08ECw, vLmXgY5Nm3frJzCsDW_5hQ...",3.59,F,32,Red Restaurant,"Automotive, Tires, Auto Parts & Supplies, Auto...",3.4,166.0,"-1.5072895, 29.0210917","-1.1214298395687634, 30.43059497249931"
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1,Syreeta,...,"bhAB5wo9iLsaExSw4apR4g, RyJsWkFLJHkf1Lif0cr3lg...",3.74,N,38,Green Store,"Tires, Auto Repair, Automotive, Oil Change Sta...",3.4,166.0,"-1.8893421, 29.2845674","-2.5160600379073057, 29.347847577202504"
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1,Laura,...,"_BcWyKQL16ndpBdggh2kNA, lGZJfjOcMOF4peqc1-YpnA...",3.84,F,31,Blue Oceans Rwanda,"Climbing, Active Life, Fitness & Instruction, ...",5.0,3.0,"-1.953642, 30.0982853","-1.9968726163206127, 29.817777424986986"

In [43]:
unique_user_ids = df['user_id'].nunique()
print(f"Number of unique user IDs: {unique_user_ids}")

Number of unique user IDs: 3178

In [36]:
# df.to_csv('the_dashboard_dataset.csv', index=False)

## distance and composite score

In [44]:
datat = pd.read_csv('the_dashboard_dataset.csv')

In [46]:
datat

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,user_name,...,friends,average_stars,gender,user_ages,business_name,categories,stars,review_count_business,business_address,user_address
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,"ZaUT63HFjheiub1y7019Yg, Obkepp5aBTYVX-AL4zwBoQ...",4.44,M,25,Gen-Z Comedy Show,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0,"-1.957937, 30.062312","-1.8131935334722813, 30.74174803504553"
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,"V9LEewSb9wmmyLeW9gEySw, zqh0Gm8TLOQmU1ayg-DPDg...",3.92,F,40,Azizi Life,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0,"-2.1479474, 29.7530937","-1.7913448254857884, 30.57414039025001"
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,"8VyYj63y30bagiHz_pqJUw, Vm0fyrUjwMTDgwqV6DhqDw...",4.41,F,38,Lavana,"Pizza, Restaurants",4.4,506.0,"-1.9600167, 30.0831264","-2.284000461592804, 29.81401787261076"
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,"llPe4d3OC8gHkXgWIAnasQ, fp9uTSoe74XLhY6HNsjEew...",4.35,F,39,KIGALI FIT,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0,"-1.9357612, 30.1099164","-2.3392663890148504, 30.648322179028003"
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,"sZaRJwINk4-V8o06kFeo2A, ZwyRFQWEzh4rGEyvlr5Oeg...",3.53,M,27,Isange One Stop Center Gahini Hospital,"Local Services, Community Service/Non-Profit, ...",0.0,0.0,"-1.8464408, 30.4770747","-2.5919683832664204, 29.048602363295014"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1,William,...,"ZQjsNntf0RQh3eJSP2EYEA, Y_2jMUKz6pvJ0JSWG3u10A...",4.17,M,32,Blue Shop,"Arts & Entertainment, Cinema",3.4,166.0,"-2.8038270, 29.0267859","-2.006153287347627, 29.434284651143"
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1,Yingbo,...,"xbhUhCSeeFg-Cm2oEIejNw, k1tSWm6mdPL-dendMa69gA...",3.47,N,29,Silver Restaurant,"Nail Salons, Beauty & Spas, Massage, Waxing, H...",3.4,166.0,"-2.5931391, 30.4458866","-2.034222796718606, 30.238543990488573"
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1,Alyse,...,"acLOor4HFm1IuyEfT08ECw, vLmXgY5Nm3frJzCsDW_5hQ...",3.59,F,32,Red Restaurant,"Automotive, Tires, Auto Parts & Supplies, Auto...",3.4,166.0,"-1.5072895, 29.0210917","-1.1214298395687634, 30.43059497249931"
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1,Syreeta,...,"bhAB5wo9iLsaExSw4apR4g, RyJsWkFLJHkf1Lif0cr3lg...",3.74,N,38,Green Store,"Tires, Auto Repair, Automotive, Oil Change Sta...",3.4,166.0,"-1.8893421, 29.2845674","-2.5160600379073057, 29.347847577202504"
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1,Laura,...,"_BcWyKQL16ndpBdggh2kNA, lGZJfjOcMOF4peqc1-YpnA...",3.84,F,31,Blue Oceans Rwanda,"Climbing, Active Life, Fitness & Instruction, ...",5.0,3.0,"-1.953642, 30.0982853","-1.9968726163206127, 29.817777424986986"

In [49]:
import pandas as pd
from geopy.geocoders import Nominatim
import time

In [50]:
# Initialize the geocoder
geolocator = Nominatim(user_agent="geoapiExercises")

# Function to get location details
def get_location_details(lat_long):
    try:
        location = geolocator.reverse(lat_long, language='en')
        address = location.raw['address']
        district = address.get('suburb', 'Not Available')
        province = address.get('state', 'Not Available')
        return district, province
    except:
        return 'Not Available', 'Not Available'


# Apply function to each address
datat[['district', 'province']] = datat['business_address'].apply(lambda x: get_location_details(x)).apply(pd.Series)

# Display the dataframe with new columns
print(datat)

                    review_id                 user_id             business_id  \
0      J-4NdnDZ0pUQaUEEwDI9KQ  vrKkXsozqqecF3CW4cGaVQ  rjuWz_AD3WfXJc03AhIO_w
1      D3GVEsKHghesOV5wdZOwRQ  Zp1o52IRl92dunmsfiT96g  gGyqnAlpFrka_qzpO7j4lQ
2      gbK7d1rp0tLKPS8oMpKFNg  oMNtNOXYFN0qdSCSfOfTOg  7sKfrJmjG6unAQeWdQUe2w
3      svljeCrxYjRHnc3obmRu3Q  RNWJx8g-TIMVn1fpNFOCvA  5kZtETKu37RuwHATrB4a5g
4      ub2BMOwKSTbhbuovib8Gtw  O7l9ox0WSrIQQoOK2fimOg  yooufdsf3eAVq_9RQNSDJA
...                       ...                     ...                     ...
13437  M_f924evEG0wzaRTVqY9pA  aBA76hKuLWuNVTS-is7fGw  U4yrxSpqLaPrGqcqok2vJg
13438  jSuM0Qgot-hGX4Qq7LkbuQ  _sWha3z3xUK_BXqjl9DPaA  OkybC0J0Qojq515LDGVRZQ
13439  7989WUKcN2PskAbPEpr1iw  f2qDQ8KnU6szwpTiaz9tVg  5cPzd9lx9-zpFvEDOr3Hjg
13440  2_gwDsYnN04D2ICLI_cU8w  p0TstOsc3Xsl_TJ3RpV01g  KDKfiyYY7VER5GUZIQoSig
13441  1_ulO0tLglmyYQfuXjPQUg  sRayUe6Y_YSXOK7pKfdlBg  IzLOX3tUTqQFBb9kHdu_wA

                                                    text                 date  \
0      I thoroughly enjoyed the show.  Chill way to s...  2012-12-04 16:46:20
1      Federal Doughnuts is a new concession at the b...  2013-04-11 04:12:06
2      I really like Franzone's. The owner is typical...  2016-07-14 23:24:19
3      This is a fabulous gym.  Considering the cost,...  2012-08-16 01:36:19
4      I feel so comfortable with the Mazzoni Center....  2016-12-19 07:32:05
...                                                  ...                  ...
13437  I came into this experience with very low expe...  2018-03-13 11:59:50
13438  Went here because of all the recent rave revie...  2015-11-13 00:33:20
13439  Glazing over the amount of unnecessary "sweeth...  2017-01-10 20:22:59
13440  This was north my best experience. I told the ...  2021-08-02 20:02:30
13441  Tons of top-roping, lead routes, and space... ...  2011-01-27 16:49:38

              service_name  state  rec_score  q_responses user_name  ...  \
0              Comedy club      1         10            1      Mike  ...
1             Food options      1          9            1   Shannon  ...
2        Restaurant dining      1          9            1     Elyse  ...
3           Gym membership      1          9            1      Sara  ...
4      Healthcare services      2          7            1       Ari  ...
...                    ...    ...        ...          ...       ...  ...
13437        Movie theater      2          8            1   William  ...
13438           Nail salon      2          8            1    Yingbo  ...
13439   Oil change service      3          4            1     Alyse  ...
13440     Tire replacement      3          1            1   Syreeta  ...
13441    Rock climbing gym      2          5            1     Laura  ...

       gender user_ages                           business_name  \
0           M        25                       Gen-Z Comedy Show
1           F        40                              Azizi Life
2           F        38                                  Lavana
3           F        39                              KIGALI FIT
4           M        27  Isange One Stop Center Gahini Hospital
...       ...       ...                                     ...
13437       M        32                               Blue Shop
13438       N        29                       Silver Restaurant
13439       F        32                          Red Restaurant
13440       N        38                             Green Store
13441       F        31                      Blue Oceans Rwanda

                                              categories  stars  \
0      Performing Arts, Arts & Entertainment, Nightli...    0.0
1      Active Life, Baseball Fields, Stadiums & Arena...    4.6
2                                     Pizza, Restaurants    4.4
3      Gyms, Trainers, Active Life, Fitness & Instruc...    4.6
4      Local Services, Community Service/Non-Profit, ...    0.0
...                                                  ...    ...
13437                       Arts & Entertainment, Cinema    3.4
13438  Nail Salons, Beauty & Spas, Massage, Waxing, H...    3.4
13439  Automotive, Tires, Auto Parts & Supplies, Auto...    3.4
13440  Tires, Auto Repair, Automotive, Oil Change Sta...    3.4
13441  Climbing, Active Life, Fitness & Instruction, ...    5.0

      review_count_business        business_address  \
0                       0.0    -1.957937, 30.062312
1                      40.0  -2.1479474, 29.7530937
2                     506.0  -1.9600167, 30.0831264
3                      37.0  -1.9357612, 30.1099164
4                       0.0  -1.8464408, 30.4770747
...                     ...                     ...
13437                 166.0  -2.8038270, 29.0267859
13438                 166.0  -2.5931391, 30.4458866
13439                 166.0  -1.5072895, 29.0210917
13440                 166.0  -1.8893421, 29.2845674
13441                   3.0   -1.953642, 30.0982853

                                  user_address       district       province
0       -1.8131935334722813, 30.74174803504553  Not Available  Not Available
1       -1.7913448254857884, 30.57414039025001  Not Available  Not Available
2        -2.284000461592804, 29.81401787261076  Not Available  Not Available
3      -2.3392663890148504, 30.648322179028003  Not Available  Not Available
4      -2.5919683832664204, 29.048602363295014  Not Available  Not Available
...                                        ...            ...            ...
13437      -2.006153287347627, 29.434284651143  Not Available  Not Available
13438   -2.034222796718606, 30.238543990488573  Not Available  Not Available
13439   -1.1214298395687634, 30.43059497249931  Not Available  Not Available
13440  -2.5160600379073057, 29.347847577202504  Not Available  Not Available
13441  -1.9968726163206127, 29.817777424986986  Not Available  Not Available

[13442 rows x 23 columns]

In [51]:
datat

,review_id,user_id,business_id,text,date,service_name,state,rec_score,q_responses,user_name,...,gender,user_ages,business_name,categories,stars,review_count_business,business_address,user_address,district,province
0,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,Comedy club,1,10,1,Mike,...,M,25,Gen-Z Comedy Show,"Performing Arts, Arts & Entertainment, Nightli...",0.0,0.0,"-1.957937, 30.062312","-1.8131935334722813, 30.74174803504553",Not Available,Not Available
1,D3GVEsKHghesOV5wdZOwRQ,Zp1o52IRl92dunmsfiT96g,gGyqnAlpFrka_qzpO7j4lQ,Federal Doughnuts is a new concession at the b...,2013-04-11 04:12:06,Food options,1,9,1,Shannon,...,F,40,Azizi Life,"Active Life, Baseball Fields, Stadiums & Arena...",4.6,40.0,"-2.1479474, 29.7530937","-1.7913448254857884, 30.57414039025001",Not Available,Not Available
2,gbK7d1rp0tLKPS8oMpKFNg,oMNtNOXYFN0qdSCSfOfTOg,7sKfrJmjG6unAQeWdQUe2w,I really like Franzone's. The owner is typical...,2016-07-14 23:24:19,Restaurant dining,1,9,1,Elyse,...,F,38,Lavana,"Pizza, Restaurants",4.4,506.0,"-1.9600167, 30.0831264","-2.284000461592804, 29.81401787261076",Not Available,Not Available
3,svljeCrxYjRHnc3obmRu3Q,RNWJx8g-TIMVn1fpNFOCvA,5kZtETKu37RuwHATrB4a5g,"This is a fabulous gym. Considering the cost,...",2012-08-16 01:36:19,Gym membership,1,9,1,Sara,...,F,39,KIGALI FIT,"Gyms, Trainers, Active Life, Fitness & Instruc...",4.6,37.0,"-1.9357612, 30.1099164","-2.3392663890148504, 30.648322179028003",Not Available,Not Available
4,ub2BMOwKSTbhbuovib8Gtw,O7l9ox0WSrIQQoOK2fimOg,yooufdsf3eAVq_9RQNSDJA,I feel so comfortable with the Mazzoni Center....,2016-12-19 07:32:05,Healthcare services,2,7,1,Ari,...,M,27,Isange One Stop Center Gahini Hospital,"Local Services, Community Service/Non-Profit, ...",0.0,0.0,"-1.8464408, 30.4770747","-2.5919683832664204, 29.048602363295014",Not Available,Not Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,M_f924evEG0wzaRTVqY9pA,aBA76hKuLWuNVTS-is7fGw,U4yrxSpqLaPrGqcqok2vJg,I came into this experience with very low expe...,2018-03-13 11:59:50,Movie theater,2,8,1,William,...,M,32,Blue Shop,"Arts & Entertainment, Cinema",3.4,166.0,"-2.8038270, 29.0267859","-2.006153287347627, 29.434284651143",Not Available,Not Available
13438,jSuM0Qgot-hGX4Qq7LkbuQ,_sWha3z3xUK_BXqjl9DPaA,OkybC0J0Qojq515LDGVRZQ,Went here because of all the recent rave revie...,2015-11-13 00:33:20,Nail salon,2,8,1,Yingbo,...,N,29,Silver Restaurant,"Nail Salons, Beauty & Spas, Massage, Waxing, H...",3.4,166.0,"-2.5931391, 30.4458866","-2.034222796718606, 30.238543990488573",Not Available,Not Available
13439,7989WUKcN2PskAbPEpr1iw,f2qDQ8KnU6szwpTiaz9tVg,5cPzd9lx9-zpFvEDOr3Hjg,"Glazing over the amount of unnecessary ""sweeth...",2017-01-10 20:22:59,Oil change service,3,4,1,Alyse,...,F,32,Red Restaurant,"Automotive, Tires, Auto Parts & Supplies, Auto...",3.4,166.0,"-1.5072895, 29.0210917","-1.1214298395687634, 30.43059497249931",Not Available,Not Available
13440,2_gwDsYnN04D2ICLI_cU8w,p0TstOsc3Xsl_TJ3RpV01g,KDKfiyYY7VER5GUZIQoSig,This was north my best experience. I told the ...,2021-08-02 20:02:30,Tire replacement,3,1,1,Syreeta,...,N,38,Green Store,"Tires, Auto Repair, Automotive, Oil Change Sta...",3.4,166.0,"-1.8893421, 29.2845674","-2.5160600379073057, 29.347847577202504",Not Available,Not Available
13441,1_ulO0tLglmyYQfuXjPQUg,sRayUe6Y_YSXOK7pKfdlBg,IzLOX3tUTqQFBb9kHdu_wA,"Tons of top-roping, lead routes, and space... ...",2011-01-27 16:49:38,Rock climbing gym,2,5,1,Laura,...,F,31,Blue Oceans Rwanda,"Climbing, Active Life, Fitness & Instruction, ...",5.0,3.0,"-1.953642, 30.0982853","-1.9968726163206127, 29.817777424986986",Not Available,Not Available